name: Release

on:
  push:
    tags:
      - v*.*.*

jobs:
  publish-package:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun ci

      - name: Build package
        run: bun run build:all

      - name: Publish package
        run: bun publish --registry https://npm.pkg.github.com
        env:
          NPM_CONFIG_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  create-release:
    needs: publish-package
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Create release
        run: gh release create ${{ github.ref_name }} --repo ${{ github.repository }} --generate-notes
